name: cat_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  firebase_core: ^1.14.1
  flutter:
    sdk: flutter

  # state
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  # UI
  modal_bottom_sheet: ^2.0.1
  # route
  go_router: ^3.0.7

  # App
  package_info_plus: ^1.4.2


dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  # lint
  pedantic_mono: ^1.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
